
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

  user:
    name: user
    password: password
  ignored: /,/css/**,/js/**,/uaa,/uaa/**,/uaa/**/**,/uaa/**/**/**,/**/*.html,/logoutall 

spring:
  mvc:
    async:
      request-timeout: 100000
  jmx:
    enabled: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000
ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 100000
  ReadTimeout: 100000

zuul:
  ignored-services: "*"
  ignored-patterns: /,/index.html,
  retryable: true
  servlet-path: /myzuul
  ignored-headers:
  sensitive-headers:
  security_headers:
  add-proxy-headers: true
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
    routeserver1:
      path: /saveroute/**
      url: http://localhost:9000/resource/saveroute
    routeserver2:
      path: /getmyroutes/**
      url: http://localhost:9000/resource/getmyroutes
    routeserver3:
      path: /getmyroutes/ownedbyme/**
      url: http://localhost:9000/resource/getmyroutes/ownedbyme
    user:
      path: /user/**
      url: http://localhost:9998/uaa/user
    uaa:
      path: /uaa/oauth/authorize/**
      url: http://localhost:9998/uaa/oauth/authorize
    #uaa1:
     # path: /uaa/login/**
     #url: http://localhost:9998/uaa/login
    uaa1:
      retryable: true
      path: /uaa/login/**
      url: http://localhost:9998/uaa/login
    ribb-login:
      path: /ribb
      url: users
    uaa3:
      path: /uaa/oauth/token/**
      url: http://localhost:9998/uaa/oauth/token
    uaa4:
      path: /uaa/css/**
      url: http://localhost:9998/uaa/css
    uaa5:
      path: /uaa/wro/**
      url: http://localhost:9998/uaa/wro
    uaa6:
      path: /uaa/js/**
      url: http://localhost:9998/uaa/js
    uaa7:
      path: /uaa/staticjs/**
      url: http://localhost:9998/uaa/staticjs
    uaa8:
      path: /uaa/signup/register/**
      url: http://localhost:9998/uaa/signup/register
    uaa9:
      path: /uaa/logoutall/**
      url: http://localhost:9998/uaa/logoutall
    friends1:
      path: /friends/addfriend/**
      url: http://localhost:9000/resource/friends/addfriend
    friends2:
      path: /friends/list/**
      url: http://localhost:9000/resource/friends/list
    friends3:
      path: /friends/del/**
      url: http://localhost:9000/resource/friends/del
    friends4:
      path: /friendrequest/addfriendreq/**
      url: http://localhost:9000/resource/friendrequest/addfriendreq
    friends5:
      path: /friendrequest/list/**
      url: http://localhost:9000/resource/friendrequest/list
    friends6:
      path: /friendrequest/del/**
      url: http://localhost:9000/resource/friendrequest/del
    friends7:
      path: /findfriends/findfriendbyusername/**
      url: http://localhost:9000/resource/findfriends/findfriendbyusername
    friends8:
      path: /findfriends/findfriendbyemail/**
      url: http://localhost:9000/resource/findfriends/findfriendbyemail
    friends9:
      path: /findfriends/findfriendbyname/**
      url: http://localhost:9000/resource/findfriends/findfriendbyname
    share1:
      path: /shareroute/sharemyroute/**
      url: http://localhost:9000/resource/shareroute/sharemyroute

     
users:
  ribbon:
    listOfServers: http://localhost:8080/ribb/

logging:
  level:
    so.pickme: debug
    so.pickme.util: error
    