
security:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/css/**,/js/**,/uaa,/uaa/**,/uaa/**/**,/uaa/**/**/**,/**/*.html,logoutall
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
  user:
    name: user
    password: password
  ignored: /,/css/**,/js/**,/uaa,/uaa/**,/uaa/**/**,/uaa/**/**/**,/**/*.html,/logoutall
   
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
    saveroute:
      path: /saveroute/**
      url: http://localhost:9000/resource/saveroute
    user:
      path: /user/**
      url: http://localhost:9998/uaa/user
    uaa:
      path: /uaa/oauth/authorize/**
      url: http://localhost:9998/uaa/oauth/authorize
    uaa1:
      path: /uaa/login/**
      url: http://localhost:9998/uaa/login
    uaa2:
      path: /logoutall
      url: http://localhost:9998/uaa/
    uaa3:
      path: /uaa/oauth/token/**
      url: http://localhost:9998/uaa/oauth/token
    uaa4:
      path: /uaa/css/**
      url: http://localhost:9998/uaa/css
    uaa5:
      path: /uaa/js/**
      url: http://localhost:9998/uaa/js
    uaa6:
      path: /uaa/
      url: http://localhost:9998/uaa/
    uaa7:
      path: /uaa/staticjs/**
      url: http://localhost:9998/uaa/staticjs
    uaa8:
      path: /uaa/signup/register/**
      url: http://localhost:9998/uaa/signup/register
    uaa9:
      path: /uaa/logoutall/**
      url: http://localhost:9998/uaa/logoutall
spring:
  aop:
    proxy-target-class: true
 
logging:
  level:
    org.springframework.security: DEBUG
